apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: itaifuchs-dev
type: Opaque
stringData:
  MONGODB_ROOT_PASSWORD: "RootP@ss123"
  MONGODB_USERNAME: "appuser"
  MONGODB_PASSWORD: "apppass"
  MONGODB_DATABASE: "appdb"
